-- создание таблицы product
CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  picture_url VARCHAR(255)
);

-- создание таблицы product_info
CREATE TABLE product_info (
  product_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DOUBLE PRECISION,
  FOREIGN KEY (product_id) REFERENCES product(id)
);

-- создание таблицы orders
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(255)
);

-- создание таблицы orders_date
CREATE TABLE orders_date (
  order_id BIGINT NOT NULL,
  status VARCHAR(255),
  date_created DATE DEFAULT CURRENT_DATE,
  FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- создание таблицы order_product
CREATE TABLE order_product (
  quantity INTEGER NOT NULL,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (product_id) REFERENCES product(id)
);
